config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events do
  	collection do
  		get 'search'
  	end
  	resources :reviews , except: [:show, :index]
  end

  root 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
	searchkick
	belongs_to :user
	has_many :reviews

	has_attached_file :image, styles: { medium: "400x600#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :reviews, dependent: :destroy



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /events
  # GET /events.json
    def search
    if params[:search].present?
      @events = Event.search(params[:search])
    else
      @events = Event.all
    end
  end

  def index
    @events = Event.all
  end

  def show
    @instagram2 = Instagram.tag_recent_media(@event.tags, {:count => 20})
    @instagram = Instagram.media_search(@event.lat,@event.lon, :min_timestamp => @event.mintime, :max_timestamp => @event.maxtime, :count => 20)

    @reviews = Review.where(event_id: @event.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end


  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :event_time, :event_date, :event_locaton, :performer, :rating, :image, :lat, :lon, :tags, :mintime, :maxtime)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_event
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.event_id = @event.id
   

    if @review.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:event_id])
    end


    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/events/_form.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@event) do |f| %>
          <% if @event.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

              <ul>
              <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group" style="color:#777;">
            <%= f.label :title %><br>
            <%= f.text_field :title , autofocus: true, class: "form-control"%>
          </div>
          <div class="form-group" style="color:#777">
            <%= f.label :description %><br>
            <%= f.text_area :description , autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group" style="color:#777">
            <%= f.label :event_time %><br>
            <%= f.time_select :event_time ,autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group" style="color:#777">
            <%= f.label :event_date %><br>
            <%= f.date_select :event_date , autofocus: true, class: "form-control"%>
            <%= f.text_field :mintime , autofocus: true, class: "form-control", placeholder: "Unix Min time"%>
            <%= f.text_field :maxtime , autofocus: true, class: "form-control", placeholder: "Unix Max time"%>
          </div>
          <div class="form-group" style="color:#777">
            <%= f.label :event_locaton %><br>
            <%= f.text_field :event_locaton , autofocus: true, class: "form-control", placeholder: "Name of the Venue" %>
            <%= f.text_field :lat , autofocus: true, class: "form-control", placeholder: "Latitude"%>
            <%= f.text_field :lon , autofocus: true, class: "form-control", placeholder: "Longitude"%>

          </div>
          <div class="form-group" style="color:#777">
            <%= f.label :performer %><br>
            <%= f.text_field :performer , autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group" style="color:#777">
            <%= f.label :Tags %><br>
            <%= f.text_field :tags , autofocus: true, class: "form-control", placeholder: "Hashtags e.g giants"%>
          </div>
          <div class="form-group" style="color:#777">
            <%= f.label :image %><br>
            <%= f.file_field :image %>
          </div>
          <center>
          <div class="actions">
            <%= f.submit "Create Event", class: "btn btn-primary"%>
          </div>
          </center>
        <% end %>
  </div>

app/views/events/edit.html.erb
<center><div id="newevent" style="color:white;font-size:36px;">Edit Event</div></center>

<%= render 'form' %>

<%= link_to 'Show', @event , class: "btn btn-primary"%> 
<%= link_to 'Back', events_path , class: "btn btn-primary" %>

app/views/events/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron" style="color:#777">
    <h1>Your Favorite Events Reviewed</h1>
    <p>FanCentral is the best way to review great experiences of the event you recently attended. FanCentral brings in the best of experiences and highlights the experiences of other Fans.</p>
    <center>
    <p>Check out how the Fans enjoyed the event</p>
      <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div></center>
<% end %>

<div class="row">
  <% @events.each do |event| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag event.image.url(:medium), class: 'image'), event %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<center><div id="newevent" style="color:white;font-size:36px;">New Event</div></center>

<%= render 'form' %>

<%= link_to 'Back', events_path , class: "btn btn-primary"%>

app/views/events/search.html.erb
<div class="row">
  <% @events.each do |event| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag event.image.url(:medium), class: 'image'), event %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">
        <h2>#<%=@event.tags%></h2>
        <div class="owl-carousel">
          <% @instagram2.each do |instagram| %>
            <%= image_tag instagram.images.thumbnail.url %>
          <% end %>
        </div>
      <br>
      <h2>Pre to Post Game</h2>
        <div class="owl-carousel">
          <% @instagram.each do |instagram| %>
            <%= image_tag instagram.images.thumbnail.url %>
          <% end %>
        </div>
          <iframe width="550" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBqYJdZitdg7oOuufOsidxT6hbzpuC3Tro%20&q=<%= @event.lat %> ,<%= @event.lon %>"></iframe>
        <h2>Game Details</h2>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @event.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @event.description %></td>
              </tr>
              <tr>
                <td><strong>Event time:</strong></td>
                <td><%= @event.event_time %></td>
              </tr>
              <tr>
                <td><strong>Event date:</strong></td>
                <td><%= @event.event_date %></td>
              </tr>
              <tr>
              <tr>
                <td><strong>Event locaton:</strong></td>
                <td><%= @event.event_locaton %></td>
              </tr>
              <tr>
              <tr>
                <td><strong>Performer</strong></td>
                <td><%= @event.performer %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <td><%= @event.rating %></td>
              </tr>
              <tr>
                <td><strong>Longitude & Latitude</strong></td>
                <td>"<%= @event.lat %> ,<%= @event.lon %>"</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-5 ">
        <h1 class="review_title"><%= @event.title %><div class="star-rating" data-score=<%= @avg_review %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em></h1>
        <%= link_to "Write a Review", new_event_review_path(@event), class: "btn btn-primary" %>
        <p><%= @event.description %></p>

        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the first!</h3>
          <%= link_to "Write Review", new_event_review_path(@event), class: "btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
        <%= image_tag @event.image.url(:medium) %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      size: 24,
      score: function() {
            return $(this).attr('data-score');
    }
  });

$(".owl-carousel").owlCarousel({
  autoPlay: 2000
});
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Fan Experience", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Event", new_event_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_events_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FanCentral</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/reviews/_form.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for([@event,@review]) do |f| %>
          <% if @review.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

              <ul>
              <% @review.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <div id="star-rating"></div>
          </div>
          <div class="form-group" style="color:#777;">
            <%= f.label :comment %><br>
            <%= f.text_area :comment , autofocus: true, class: "form-control"%>
          </div>
          <div class="form-group" style="color:#777;">
            <%= f.submit "Submit Review", class: "btn btn-primary"%>
          </div>
        <% end %>
      </div>
      </div>
      </div>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', event_path(@event) %> |

app/views/reviews/new.html.erb
<center><div id="newevent" style="color:white;font-size:36px;">New Review</div></center>

<%= render 'form' %>

<%= link_to 'Back', "#" %>